In [1]:
import numpy as np

In [2]:
it = [3, 6, 7, 11]

In [5]:
n = np.array(it)

In [6]:
type(n)

numpy.ndarray

In [8]:
twod = np.array([[1, 2], [3, 4]])
twod

array([[1, 2],
       [3, 4]])

In [15]:
y = np.array([2, 5, 6, "77"])
y

array(['2', '5', '6', '77'], dtype='<U21')

In [16]:
list(range(9, 16))

[9, 10, 11, 12, 13, 14, 15]

In [17]:
list(range(9,16,2)) # start from 9 go till 15 with a jump of 2 in between every element

[9, 11, 13, 15]

In [18]:
np.arange(9,16) #range implementation of numpy

array([ 9, 10, 11, 12, 13, 14, 15])

In [19]:
np.arange? # you don't have to remember everything.....doctrings come in handy.

Docstring:
arange([start,] stop[, step,], dtype=None, *, like=None)

Return evenly spaced values within a given interval.

Values are generated within the half-open interval ``[start, stop)``
(in other words, the interval including `start` but excluding `stop`).
For integer arguments the function is equivalent to the Python built-in
`range` function, but returns an ndarray rather than a list.

When using a non-integer step, such as 0.1, the results will often not
be consistent.  It is better to use `numpy.linspace` for these cases.

Parameters
----------
start : integer or real, optional
    Start of interval.  The interval includes this value.  The default
    start value is 0.
stop : integer or real
    End of interval.  The interval does not include this value, except
    in some cases where `step` is not an integer and floating point
    round-off affects the length of `out`.
step : integer or real, optional
    Spacing between values.  For any output `out`, this is the distance
  

In [26]:
np.arange(100).reshape(10, 10)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [27]:
# one interesting way to use arange

arr1 = np.arange(40)

In [30]:
arr2 = arr1.reshape(8, 5)
arr2

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39]])

In [31]:
arr1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39])

In [34]:
arr1[0]= 1000
arr1

array([1000,    1,    2,    3,    4,    5,    6,    7,    8,    9,   10,
         11,   12,   13,   14,   15,   16,   17,   18,   19,   20,   21,
         22,   23,   24,   25,   26,   27,   28,   29,   30,   31,   32,
         33,   34,   35,   36,   37,   38,   39])

In [33]:
arr2

array([[1000,    1,    2,    3,    4],
       [   5,    6,    7,    8,    9],
       [  10,   11,   12,   13,   14],
       [  15,   16,   17,   18,   19],
       [  20,   21,   22,   23,   24],
       [  25,   26,   27,   28,   29],
       [  30,   31,   32,   33,   34],
       [  35,   36,   37,   38,   39]])

In [7]:
# BROADCASTING IN NUMPY - 

a = np.random.randint(1, 100, (2, 4)) # randint(low, high, size of array)
a

array([[63, 30, 68,  8],
       [ 3, 19, 97,  3]])

In [6]:
b = np.random.randint(1, 100, (2,4))
b

array([[52, 51, 23, 60],
       [93, 69, 26, 83]])

In [8]:
a + b # adds the elements of array a and b. This is known as broadcasting.

array([[115,  81,  91,  68],
       [ 96,  88, 123,  86]])

In [9]:
# Now let's play with broadcasting a little.

In [10]:
a = np.random.randint(1, 100, (4, 1))
b = np.random.randint(1, 100, (2, 4))

In [11]:
a+b

ValueError: operands could not be broadcast together with shapes (4,1) (2,4) 

In [12]:
a = np.random.randint(1, 100, (2, 1))
b = np.random.randint(1, 100, (2, 4))

In [13]:
a + b

array([[127, 161,  86, 149],
       [152, 138, 109,  93]])

In [16]:
a = np.random.randint(1, 100, (4))
b = np.random.randint(1, 100, (3, 4))

In [17]:
a + b

array([[ 66,  73, 113, 118],
       [ 84, 136, 104, 102],
       [106, 128,  69,  53]])

In [18]:
# 2 Rules :-

In [21]:
# - shape should be same, start checking from right (inner part) and go towards the left
# - if it has 1 in it, then cool